gigs/portal/urls.py
from django.conf.urls.defaults import *
from django.conf.urls import include
from django.views.generic import DetailView, ListView, TemplateView
from gigs.gig_registry.models import Gig, Band, Venue, Location
from django.contrib.auth.views import logout

urlpatterns = patterns(
    'gigs.portal.views',
    url(r'^$', TemplateView.as_view(template_name='portal/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='portal/about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='portal/contact.html'), name='contact'),
    url(r'^gig/(?P<pk>\d+)/$', DetailView.as_view(model=Gig, template_name="portal/gig_detail.html"), name='portal_gig_detail'),
    url(r'^band/(?P<pk>\d+)/$', DetailView.as_view(model=Band, template_name="portal/band_detail.html"), name='portal_band_detail'),
    url(r'^venue/(?P<pk>\d+)/$', DetailView.as_view(model=Venue, template_name="portal/venue_detail.html"), name='portal_venue_detail'),
    url(r'^location/(?P<pk>\d+)/$', DetailView.as_view(model=Location, template_name="portal/location_detail.html"), name='portal_location_detail'),
    url(r'^tugging/$', TemplateView.as_view(template_name='portal/tugging.html'), name='tugging'),
    url(r'^login/$', 'portal_login', name='login'), 
    url(r'^logout/$', logout, {'next_page':'/'}, name='logout'), 
)

gigs/urls.py
from django.conf.urls.defaults import *
from django.http import HttpResponse

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from gigs.portal import urls as portal_urls
from gigs.search import urls as search_urls
from gigs.gig_registry.models import Gig, Venue, Location

admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'', include(portal_urls)),
    (r'^admin/', include(admin.site.urls)),
    (r'^index/', include(search_urls)),
    (r'^export_gigs/$', 'django_tablib.views.export', {
            'model': Gig,
            }),
    (r'^export_venues/$', 'django_tablib.views.export', {
            'model': Venue,
            }),
    (r'^export_locations/$', 'django_tablib.views.export', {
            'model': Location,
            }),
    (r'^gig_csv_subset/', 'gigs.portal.views.get_gigs_data'),
    (r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain"))
        )
)

gigs/gig_registry/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.template.defaultfilters import date as _date
from django.contrib import auth
from django.core.urlresolvers import reverse

import datetime


class SourceType(models.Model):
    name = models.CharField(max_length=40, unique=True)

    def __unicode__(self):
        return self.name

class Source(models.Model):
    name = models.CharField(max_length=40)
    author = models.CharField(max_length=100, blank=True, null=True)
    published = models.DateField()
    added_by = models.ForeignKey(auth.models.User, blank=True, null=True)
    source_type = models.ForeignKey(SourceType, blank=True, null=True)

    class Meta:
        unique_together = ('name', 'published')

    def __unicode__(self):
        rep = "%s, %s" % (self.name, self.published)
        if self.source_type:
            rep = rep + " (%s)" % (self.source_type)
        return rep

class UUIDManager(models.Manager):
    prefix = ''
    numbers_length = 7
    def get_next_UUID(self):
        next_number = 0
        for item in self.get_query_set().all().order_by('-uuid'):
            if not item.uuid:
                continue
            numeric_substring = item.uuid[1:]
            try:
                next_number = int(numeric_substring) + 1
                if next_number >= 10 ** (self.numbers_length -1):
                    continue
                break
            except ValueError:
                pass
        return "%s%s" % (self.prefix, str(next_number).zfill(self.numbers_length))

class GigUUIDManager(UUIDManager):
    prefix = 'G'

class PersonUUIDManager(UUIDManager):
    prefix = 'P'

class BandUUIDManager(UUIDManager):
    prefix = 'B'

class LocationUUIDManager(UUIDManager):
    prefix = 'L'

class VenueUUIDManager(UUIDManager):
    prefix = 'V'

class Person(models.Model):
    uuid = models.CharField(max_length=40, unique=True)
    created_at = models.DateField(default=datetime.date.today)
    updated_at = models.DateField(blank=True, null=True)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    nick_name = models.CharField(max_length=40, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    comment = models.TextField(max_length=300, blank=True)


    def __unicode__(self):
        name = [self.first_name, self.last_name]

        if self.nick_name:
            return (" '%s' " % self.nick_name).join(name)

        return " ".join(name)

class Manager(Person):
    pass

class Musician(Person):
    instrument = models.CharField(max_length=50, blank=True)
    objects = PersonUUIDManager()

class Owner(Person):
    # Not sure if this will be a thing yet. Just a placeholder
    pass

class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.name

class Band(models.Model):
    uuid = models.CharField(max_length=40, null=True, blank=True)
    created_at = models.DateField(default=datetime.date.today)
    updated_at = models.DateField(blank=True, null=True)
    name = models.CharField(max_length=50)
    genre = models.ManyToManyField(Genre, blank=True, null=True)
    members = models.ManyToManyField(Musician, through='BandMembership', blank=True, null=True)
    founded = models.DateField(blank=True, null=True)
    comment = models.TextField(max_length=300, blank=True)

    objects = BandUUIDManager()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('portal_band_detail', args=[str(self.id)])

class BandMembership(models.Model):
    started = models.DateField()
    finished = models.DateField(blank=True, null=True)
    band = models.ForeignKey(Band)
    musician = models.ForeignKey(Musician)

    def __unicode__(self):
        return '%s in %s (%s to %s)' % (
                    self.musician,
                    self.band ,
                    self.started,
                    self.finished if self.finished else 'present')

class LocationManager(LocationUUIDManager):


    def _filter_instance_or_queryset(self, field, instances):
        if isinstance(instances, (QuerySet, list,)):
            field += '__in'
        filter_set = {field: instances}
        return Location.objects.filter(**filter_set).distinct()

    def for_bands(self, band):
        return self._filter_instance_or_queryset('venue__gig__bands', band)

    def for_venues(self, venue):
        return self._filter_instance_or_queryset('venue', venue)

    def for_gigs(self, gigs):
        return self._filter_instance_or_queryset('venue__gig', gigs)

class Location(models.Model):
    uuid = models.CharField(max_length=40, unique=True)
    created_at = models.DateField(default=datetime.date.today)
    updated_at = models.DateField(blank=True, null=True)
    # this will be replaced with geodjango
    building_name = models.CharField(max_length=150, blank=True, null=True)
    street_address = models.CharField(max_length=150)
    country = models.CharField(max_length=150)
    state = models.CharField(max_length=150)
    suburb = models.CharField(max_length=150)
    post_code  = models.CharField(max_length=150)
    comment = models.TextField(max_length=300, blank=True)
    lat = models.DecimalField(max_digits=12, decimal_places=6, verbose_name='latitude', blank=True, null=True)
    lon = models.DecimalField(max_digits=12, decimal_places=6, verbose_name='longitude', blank=True, null=True)

    objects = LocationManager()

    def __unicode__(self):
        return "%s, %s %s, %s %s" % (
                self.street_address,
                self.suburb,
                self.state,
                self.post_code,
                self.country
                )

class Stage(models.Model):
    name = models.CharField(max_length=50)
    capacity = models.IntegerField(blank=True)

    def __unicode__(self):
        return self.name

class Venue(models.Model):
    STATUS_CHOICES = (
            ('O', 'Open'),
            ('C', 'Closed'),
            )
    uuid = models.CharField(max_length=40, unique=True)
    name = models.CharField(max_length=50)
    location = models.ForeignKey(Location)
    established = models.IntegerField(blank=True, null=True)
    stages = models.ManyToManyField(Stage, blank=True, null=True)
    venue_type = models.CharField(max_length=50, blank=True)# TODO: make this a set list or fk
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='O')
    status_notes = models.CharField(max_length=300, blank=True)
    comment = models.TextField(max_length=300, blank=True)

    objects = VenueUUIDManager()

    def __unicode__(self):
        if self.name:
            return self.name
        return 'Unnamed venue'

class GigType(models.Model):
    name = models.CharField(max_length=40, unique=True)

    def __unicode__(self):
        return self.name

#class GigUUIDManager(models.Manager):
#    def get_next_UUID(self):
#        max_uuid = self.get_query_set().all().order_by('-uuid')[0].uuid
#        next_number = int(max_uuid[1:]) + 1
#        return "G%s" % (str(next_number).zfill(7))


class Gig(models.Model):

    uuid = models.CharField(max_length=40, unique=True)
    created_at = models.DateField(default=datetime.date.today)
    updated_at = models.DateField(blank=True, null=True)
    start = models.DateField()
    finish = models.DateField(blank=True, null=True)
    venue = models.ForeignKey(Venue)
    name  = models.CharField(max_length=150, blank=True)
    cost = models.FloatField(blank=True, null=True)
    gig_type = models.ForeignKey(GigType, blank=True, null=True)
    comment = models.TextField(max_length=300, blank=True)
    source = models.ForeignKey(Source, blank=True, null=True)

    # TODO members can be absent on the night..is this a problem?
    # maybe an 'appearance' model or something like that?
    bands = models.ManyToManyField(Band, through='Performance')

    objects = GigUUIDManager()

    def __unicode__(self):
        if self.name:
            return self.name
        name = ""
        if self.bands.count():
            name = ', '.join([band.name for band in self.get_headlining_bands()])
            if self.get_non_headlining_bands():
                name += " and others"

        if self.venue:
            name +=  " @ " + self.venue.name

        if self.start:
            name += " on %s " % _date(self.start, "l, M j Y")

        if not name:
            name = "No bands and no venue specified"
        return name

    def get_headlining_bands(self):
        return self.bands.filter(performance__order=Performance.HEADLINER)

    def get_non_headlining_bands(self):
        return [p.band for p in Performance.objects.\
                exclude(order=Performance.HEADLINER).\
                filter(gig=self).order_by('order')]


class Performance(models.Model):
    HEADLINER       = 1
    FIRST_SUPPORT   = 2
    SECOND_SUPPORT  = 3
    THIRD_SUPPORT   = 4
    FOURTH_SUPPORT  = 5
    FIFTH_SUPPORT   = 6
    SIXTH_SUPPORT   = 7
    SEVENTH_SUPPORT = 8
    EIGTH_SUPPORT   = 9
    NINTH_SUPPORT   = 10
    TENTH_SUPPORT   = 11

    ORDER_CHOICES = (
            (HEADLINER, 'Headliner'),
            (FIRST_SUPPORT, 'First support'),
            (SECOND_SUPPORT, 'Second support'),
            (THIRD_SUPPORT, 'Third support'),
            (FOURTH_SUPPORT, 'Fourth support'),
            (FIFTH_SUPPORT, 'Fifth support'),
            (SIXTH_SUPPORT, 'Sixth support'),
            (SEVENTH_SUPPORT, 'Seventh support'),
            (EIGTH_SUPPORT, 'Eigth support'),
            (NINTH_SUPPORT, 'Ninth support'),
            (TENTH_SUPPORT, 'Tenth support'),
            )
    band = models.ForeignKey(Band)
    gig = models.ForeignKey(Gig)
    order = models.IntegerField(choices=ORDER_CHOICES, default=1)
    time = models.TimeField(null=True, blank=True)
    genre = models.ManyToManyField(Genre, blank=True, null=True)

gigs/portal/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response

from django.http import Http404, HttpResponse
from django_tablib.base import mimetype_map

from gigs.portal.datasets import ModelRelatedDataset
from gigs.gig_registry import models
from gigs.search.views import basic_search


def portal_login(request):

    error = False
    form = None

    if request.method == 'POST':
        #form = AuthenticationForm(request.POST)
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = None
        #if form.is_valid():
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        error = True

    form = AuthenticationForm()
    c = RequestContext(request, {'form':form, 'error': error})

    return render_to_response('portal/portal_login.html', c)


def export(request, queryset=None, model=None, headers=None, format='xls',
           filename='export'):
    if queryset is None:
        queryset = model.objects.all()

    dataset = ModelRelatedDataset(queryset)
    filename = '%s.%s' % (filename, format)
    if not hasattr(dataset, format):
        raise Http404
    response = HttpResponse(
        getattr(dataset, format),
        mimetype=mimetype_map.get(format, 'application/octet-stream')
        )
    response['Content-Disposition'] = 'attachment; filename=%s' % filename
    return response


def get_gigs_data(request):
    queryset = models.Gig.objects.all()
    if request.GET.get('q', None):
        search_queryset = basic_search(request, template=None, load_all=True)
        gig_ids = [search_result.object.id for search_result in search_queryset]
        queryset = queryset.filter(pk__in=gig_ids)

    headers = [
            'venue.id',
            'venue.name',
            'venue.location.id',
            'venue.location.street_address',
            ]

    return export(request, queryset=queryset, headers=headers)

gigs/portal/templates/portal/about.html
{% extends "portal/portal_base.html" %}

{% block content %}

{% include "portal/overview.html" %}

{% comment %}
{% include "portal/stats.html" %}

{% include "portal/license.html" %}
{% endcomment %}
{% endblock %}

gigs/portal/templates/portal/band_detail.html
{% extends "portal/detail_base.html" %}
{% load maps %}
{% load bands %}

{% block detail_hint %}
Try exploring further by clicking on a gig this band played or a related band
{% endblock %}

{% block content %}
<div id="band-info">
  <h2>Band details</h2>
  <div id="band-properties" >

      <span class="detail-heading">Band name: <b>{{band.name}}</b></span>
    <table>
      <tr><td>Years performing:</td><td>Not listed</td></tr>
      <tr><td>Members:</td>
        <td>
        {% if band.members.count %}
        {% for member in band.members.all %}
          {{member}}{% if not forloop.last %},{% endif %}
        {% endfor %}
        {% else %}
          No members currently listed
        {% endif %}
        </td>
      </tr>
    </table>
  </div>
  <form action="/gig_csv_subset/">
    <input type=hidden name=q value={{query}}>
    <p>
      <button type="post" id="download-csv-btn"></button>
      Download these gig listing as a CSV file.
    </p>
  </form>
</div>
{% endblock %}

{% block right-bar %}
  <div class="side-detail">
  {% bands_played_with band %}
  {% if band|has_locations %}
  <div id="map-container">
    <h3 class="map-heading">GIG MAP</h3>
    {% map band %}
  </div>
  {% endif %}
  </div>
{% endblock %}

gigs/portal/templates/portal/basic_band_info.html
<p><span class="detail-title">Name: </span><a href = "{% url "portal_band_detail" band.id %}">{{band.name}}</a></strong></p>
<p><span class="detail-title">Members: </span>{% if band.members.count %}{% for member in band.members.all %}{{member}}{% endfor %}{% else %}No band members listed{% endif %}</p>

gigs/portal/templates/portal/basic_location_info.html
<div id="location-info" class="detail-info-list">
  <a href="{% url "portal_location_detail" location.id %}">
    <address>
      <strong>{{venue.location.name}}</strong>
      <br>
      {{location.street_address}}
      <br>
      {{location.suburb}}, {{location.postcode}}
      <br>
      {{location.country}}
    </address>
  </a>
</div><!-- location-info -->

gigs/portal/templates/portal/basic_venue_info.html
<div id="venue-info" class="detail-info-list">
      <a href="{% url portal_venue_detail" venue.id %}">{{venue.name}}</a><br/>
      Status: {{venue.get_status_display}}<br/>
      Type: {% if venue.venue_type %}{{venue.venue_type}}{% else %}No venue type specified{% endif %}<br/>
      <address>Location:
        
        <a href="{% url "portal_location_detail" venue.location.id %}">
          <strong>{{venue.location.name}}</strong>
          {{venue.location.street_address}}
          {{venue.location.suburb}}<!-- , {{location.postcode}} -->
        </a>
        </address>
      
      Comments: {% if venue.comment %} {{venue.comment}} {% else %} <span class="no-comments">No comments</span>{% endif %}
{% comment %}
    Not sure whether to modify basic_location_info or not.
    <div id="location-info" class="row">
      <h2>Location</h2>
    {% if venue.location %}
      {% with venue.location as location %}
      {% include "portal/basic_location_info.html" %}
      {% endwith %}
    {% else %}
    <p>No location listed for this venue</p>
    {% endif %}
  </div><!-- location-info -->
{% endcomment %}
</div><!-- venue-info -->

gigs/portal/templates/portal/contribute.html
<a href="mailto:{{contact_email}}?subject={{subject}}">Contribute to TUGG</a>

gigs/portal/templates/portal/gig_detail.html
{% extends "portal/detail_base.html" %}
{% load maps %}
{% load search_results %}

{% block detail_hint %}
Try exploring further by clicking on a supporting band or on a venue to find out more.
{% endblock %}

{% block content %}
<div id="gig-info">
  <h2>Gig Details</h2>
  <div id="gig-properties">
    <span class="detail-heading">Gig name: <b>{{gig}}</b></span>
    {% comment %} Where can this go?   <p><strong>start time:</strong> {{gig.start|date:"l, M j, Y"}}</p> {% endcomment %}
  </div>
  <div id="bands">
    {% for band in gig.get_headlining_bands %}
      {% if forloop.first %}
      <div class="detail-heading">Headlining band</div>
      {% endif %}
      {% include "portal/basic_band_info.html" %}
    {% endfor %}
    {% for band in gig.get_non_headlining_bands %}
    <div class="band{% if forloop.last %} last{% endif %}">
      {% if forloop.first %}
      <div class="detail-heading">Other bands</div>
      {% endif %}
      {% include "portal/basic_band_info.html" %}
    </div>
      {% endfor %}
  </div><!-- bands -->
  <!-- ###TODO is this actually meaningful? download a single record? -->
  <form action="/gig_csv_subset/">
    <input type=hidden name=q value={{query}}>
    <p>
      <button type="post" id="download-csv-btn"></button>
      Download this gig listing as a CSV file.
    </p>
  </form>
</div><!-- gig-info -->
{% endblock %}

{% block right-bar %}
  <div id="venue-details" class="side-detail">
    <div class="detail-heading">Venue details</div>
   {% if gig.venue %}
   {% with gig.venue as venue %}
   {% include "portal/basic_venue_info.html" %}
   {% endwith %}
   {% if gig|has_locations %}
   <div id="map-container">
     <h3 class="map-heading">GIG MAP</h3>
     {% map gig %}
   </div>
   {% endif %}
   {% else %}
   <p>No Venue listed for this gig</p>
   {% endif %}
   </div><!-- side-detail -->
{% endblock %}

gigs/portal/templates/portal/gig_row.html
<tr>
    <td><a href="{% url "portal_gig_detail" gig.id %}"><i class="icon-zoom-in"></i></a></td>
    <td>{{gig.start|date:"l, M j, Y"}}</td>
    <td><a href="{% url "portal_venue_detail" gig.venue.id %}">{{gig.venue.name}}</a></td>
    <td>
    <div class="accordian" id="band-list-accordian">    
      <div class="accordian-group">
        {% for band in gig.bands.all %}
        {% if forloop.first %}
        <div class "accordian-heading">
            <a href="{% url "portal_band_detail" band.id %}">{{band.name}}</a>
            {% if gig.bands.count|add:-1%}
            <a class="accordian-toggle" data-toggle="collapse" data-parent="#band-list-accordian" href="#collapse-{{gig.id}}">({{gig.bands.count|add:-1}} other{{gig.bands.count|add:-1|pluralize}})</a> 
            {% endif %}
        </div>
        <div id="collapse-{{gig.id}}" class="accordion-body collapse">
        <div class="accordian-inner">
        {% else %}
        <a href="{% url "portal_band_detail" band.id %}">{{band.name}}</a><br/>
        {% endif %}
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
  </td>
  <td><a href="{% url "portal_gig_detail" gig.id %}">{% if gig.name %}{{gig.name}}{% else %}(None){% endif %}</a></td>
  <td>{% if gig.cost %}{{gig.cost}}{% else %}(Not specified){% endif %}</td>
  <td><a href="{% url "portal_venue_detail" gig.venue.id %}">{{gig.venue.location}}</a></td>
</tr>

gigs/portal/templates/portal/index.html
{% extends "portal/portal_base.html" %}
{% block script %}
{{ block.super }}
<script src="/static/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script type="text/javascript">
/* API method to get paging information */
$.fn.dataTableExt.oApi.fnPagingInfo = function ( oSettings )
{
    return {
        "iStart":         oSettings._iDisplayStart,
        "iEnd":           oSettings.fnDisplayEnd(),
        "iLength":        oSettings._iDisplayLength,
        "iTotal":         oSettings.fnRecordsTotal(),
        "iFilteredTotal": oSettings.fnRecordsDisplay(),
        "iPage":          Math.ceil( oSettings._iDisplayStart / oSettings._iDisplayLength ),
        "iTotalPages":    Math.ceil( oSettings.fnRecordsDisplay() / oSettings._iDisplayLength )
    };
}
 
/* Bootstrap style pagination control */
$.extend( $.fn.dataTableExt.oPagination, {
    "bootstrap": {
        "fnInit": function( oSettings, nPaging, fnDraw ) {
            var oLang = oSettings.oLanguage.oPaginate;
            var fnClickHandler = function ( e ) {
                e.preventDefault();
                if ( oSettings.oApi._fnPageChange(oSettings, e.data.action) ) {
                    fnDraw( oSettings );
                }
            };
 
            $(nPaging).addClass('pagination').append(
                '<ul>'+
                    '<li class="prev disabled"><a href="#">&larr; '+oLang.sPrevious+'</a></li>'+
                    '<li class="next disabled"><a href="#">'+oLang.sNext+' &rarr; </a></li>'+
                '</ul>'
            );
            var els = $('a', nPaging);
            $(els[0]).bind( 'click.DT', { action: "previous" }, fnClickHandler );
            $(els[1]).bind( 'click.DT', { action: "next" }, fnClickHandler );
        },
 
        "fnUpdate": function ( oSettings, fnDraw ) {
            var iListLength = 5;
            var oPaging = oSettings.oInstance.fnPagingInfo();
            var an = oSettings.aanFeatures.p;
            var i, j, sClass, iStart, iEnd, iHalf=Math.floor(iListLength/2);
 
            if ( oPaging.iTotalPages < iListLength) {
                iStart = 1;
                iEnd = oPaging.iTotalPages;
            }
            else if ( oPaging.iPage <= iHalf ) {
                iStart = 1;
                iEnd = iListLength;
            } else if ( oPaging.iPage >= (oPaging.iTotalPages-iHalf) ) {
                iStart = oPaging.iTotalPages - iListLength + 1;
                iEnd = oPaging.iTotalPages;
            } else {
                iStart = oPaging.iPage - iHalf + 1;
                iEnd = iStart + iListLength - 1;
            }
 
            for ( i=0, iLen=an.length ; i<iLen ; i++ ) {
                // Remove the middle elements
                $('li:gt(0)', an[i]).filter(':not(:last)').remove();
 
                // Add the new list items and their event handlers
                for ( j=iStart ; j<=iEnd ; j++ ) {
                    sClass = (j==oPaging.iPage+1) ? 'class="active"' : '';
                    $('<li '+sClass+'><a href="#">'+j+'</a></li>')
                        .insertBefore( $('li:last', an[i])[0] )
                        .bind('click', function (e) {
                            e.preventDefault();
                            oSettings._iDisplayStart = (parseInt($('a', this).text(),10)-1) * oPaging.iLength;
                            fnDraw( oSettings );
                        } );
                }
 
                // Add / remove disabled classes from the static elements
                if ( oPaging.iPage === 0 ) {
                    $('li:first', an[i]).addClass('disabled');
                } else {
                    $('li:first', an[i]).removeClass('disabled');
                }
 
                if ( oPaging.iPage === oPaging.iTotalPages-1 || oPaging.iTotalPages === 0 ) {
                    $('li:last', an[i]).addClass('disabled');
                } else {
                    $('li:last', an[i]).removeClass('disabled');
                }
            }
        }
    }
} );

$(document).ready(function() {
        $('#index-table').dataTable({
        "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
        "sPaginationType": "bootstrap",
        "bFilter": false,
        "bInfo": false,
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "{% url search_ajax %}{% if query %}q={{query}}{% endif %}"
    } );
});

$.extend($.fn.dataTableExt.oStdClasses, {
    "sWrapper": "dataTables_wrapper form-inline"
    });
</script>
{% endblock %}

{% block content %}
<div class="row-fluid">
    <h1>The Gig List</h1>
    <br>
</div>
<br>
<div class="row-fluid">
    {% load maps %}
    {% map gig_list %}
    <br/>
    <form action="/gig_csv_subset/">
    <p>
    <input type=hidden name=ids value={% for g in gig_list %}{% if not forloop.first %},{% endif %}{{g.pk}}{% endfor %}>
      <button class="btn btn-large btn-primary btn-block" type="post">Download results</button>
      </p>
      </form>
  <table class="table table-bordered" id="index-table">
    <thead>
        <tr><th></th><th>Date</th/><th>Venue Name</th><th>Bands</th><th>Gig Name</th/><th>Cost</th/><th>Address</th/></tr>
    </thead>
    <tbody>
    {% for gig in gig_list %}
      {% include "portal/gig_row.html" %}
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

{% block right-bar %}
    Right stuff.
    {% include "search/search_form.html" %}  
{% endblock %}

gigs/portal/templates/portal/license.html
<p>Site content &copy; Deakin University, VeRSI 2012</p>
<p>Some images &copy; James Verhoeven 2012</p>

gigs/portal/templates/portal/location_detail.html
{% extends "portal/detail_base.html" %}
{% load maps %}

{% block detail_hint %}
{% endblock %}

{% block content %}
<div id="location-info">
 <h2>Location details</h2>
  <div id="location-properties" >
    <span class="detail-heading">Address: <b>{{location}}</b></span>
  </div>
</div>
{% endblock %}

{% block right-bar %}
<div class="side-detail">
  <div id="map-container">
    <h3 class="map-heading">LOCATION</h3>
    {% map location %}
  </div>
</div>
{% endblock %}

gigs/portal/templates/portal/venue_detail.html
{% extends "portal/detail_base.html" %}
{% load maps %}
{% load search_results %}

{% block detail_hint %}
Try exploring further by clicking on a supporting band or on a venue to find out more.
{% endblock %}

{% block content %}
<div id="venue-info">
  <h2>Venue Details</a></h2>
  <div id="venue-properties">
    <p><span class="detail-heading">Name: <b>{{venue.name|default:"None"}}</b></span>
    <p>Status: {{venue.get_status_display|default:"None"}}
    <p>Type of venue:{{venue.type|default:"None"}}
    <p>Comment:{{venue.comment|default:"None"}}
  </div><!-- venue-properties -->
</div><!-- venue-info -->
<form action="/gig_csv_subset/">
    <input type=hidden name=q value="{{venue.name}}"> {% comment %} #TODO fetch related gigs using fields {% endcomment%}
    <p>
      <button type="post" id="download-csv-btn"></button>
      Download this gig listing as a CSV file.
    </p>
  </form>
{% endblock %}

{% block right-bar %}
<div id="location-details" class="side-detail">
  <div class="detail-heading">Location details</div>
  {% if venue|has_locations %}
  {% with venue.location as location %}
  {% include "portal/basic_location_info.html" %}
  {% endwith %}
  <div id="map-container">
    <h3 class="map-heading">VENUE MAP</h3>
    {% map venue %}
  </div><!-- map-container -->
   {% else %}
  <p>No location listed</p>
   {% endif %}
</div><!-- location-details -->
{% endblock %}